twist_mux:
  ros__parameters:
    topics:
      nav:
        topic: /cmd_vel
        timeout: 0.5
        priority: 20
      joy:
        topic: /cmd_vel_joy_safe
        timeout: 0.5
        priority: 90
      grasp:
        topic: /grasp/cmd_vel
        timeout: 1.0
        priority: 80
