# ~/Documents/02_ROS2/ros2_humble_ws/yaml/teleop_switch.yaml
teleop_twist_joy_node:
  ros__parameters:
    # --- AXES (typical for Switch Pro on Linux) ---
    axis_linear.x: 1        # Left stick vertical (forward/back)
    axis_linear.y: 0        # Left stick horizontal (strafe; set scale 0.0 if not holonomic)
    axis_angular.z: 3       # Right stick horizontal (turn)

    # --- SPEED SCALING ---
    scale_linear.x: 0.5
    scale_linear.y: 0.5     # set 0.0 if your base isn’t holonomic
    scale_angular.z: 0.5
    scale_linear_turbo.x: 1.0
    scale_linear_turbo.y: 1.0
    scale_angular_turbo.z: 1.0

    # --- SAFETY / ENABLE ---
    require_enable_button: true
    enable_button: 5        # R button as deadman (hold to move)
    enable_turbo_button: 7  # ZR as turbo (optional)

    # (optional but helpful)
    enable_turbo: false
